language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
before_script:
  - go get -d ./...
script:
  - go test -v ./... -bench=.

  - go test -coverprofile=message.coverprofile ./message
  - go test -coverprofile=queue.coverprofile ./queue
  - go test -coverprofile=udp.coverprofile ./udp
  - go test -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci

  - go build main/agora.go

deploy:
  provider: releases
  api_key:
    secure: g69DJJJjOF0YP7ZA4nJYSuLja3kz001N7d/n5hazMi3lkWOwZVXMqJYcir3/vqVtLP4k36mdpfpRHrKo9zyf228tvICyEG/nHcIlm4u7XJZoXfXlwR8aT8d2OGSQAKu85lH6SSxdT271Xef9YPvLFYsKoAXnyUPp0G6PLuW0UhR9hqQ9VweQKiqPssFDOi2kP5mhUIeNGBOKRiBIPVybzDoWUjVYY4hgbOCtrKvspcOSy1lcHINIFubdpFoUViiaV95vuVbFTQLYny/xDsC06Q8LI9HfT0iQCdk9W85Xndy4d/vt0RtZkbsKe+3dQlhwWlMe4/MMnvm38u6ip2EuFw3TperiGdsMXglGrGF6JmEw0ZSKMSzEYa3C26JCtVtctUiBfVasBqHoyRvmPDIimRa2FjHWgUixCUxENqDlZ04wXrp6zpIB8z8qREVJCmp7/rr3w/Ra8+nTHyI3PbP4dPJ/BE1YkagPs8V31VBvMv9ARQiaGqC7ZL9cZ3ZpppLJaq+xpTj3mdWJuAAd52JppGOFq9QPUJluiWvlsKvbn3zRlR8g2o2CP8r3iZ1doFhSyLQqp6XrHt4dPVsBBLm3s1iGSFGkJ6ifJ4kU4TR+zl0hr2v40MC1kJZeOesSQ29qIukWRBdFb+xChey/kWQOPDY9qNDcBpkrE4BcfgS90S4=
  file: Agora
  skip_cleanup: true
  on:
    repo: verma-kartik/Agora
    branch: main
    go: '1.9'
    tags: true