version: 2.1

jobs:
  build:
    working_directory: ~/github.com/verma-kartik/Agora
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/axw/gocov/gocov
      - run: go get github.com/modocache/gover
      - run: go get github.com/mattn/goveralls
      - run: go get -d ./...
      - run: go test -v ./... -bench=.
      - run: go test -coverprofile=message.coverprofile ./message
      - run: go test -coverprofile=queue.coverprofile ./queue
      - run: go test -coverprofile=main.coverprofile
      - run: $HOME/gopath/bin/gover
      - run: $HOME/gopath/bin/goveralls -coverprofile=$HOME/gopath/coverage.out -service=circle-ci -repotoken=wmawIpg8vk25Tbw2Ie1Jyrh9rynUEnsH6
      - run: go build main/agora.go

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
